name: Upload Binaries
on:
  workflow_call:
    inputs:
      matrix:
        type: string
        required: true
      release_tag:
        type: string
        required: false
      release_prerelease:
        type: boolean
        required: false
    secrets:
      token:
        required: true

jobs:
  Artifacts:
    name: ${{ matrix.config.name }} ${{ matrix.binaries }}
    runs-on: ubuntu-latest
    env:
      EXT: ${{ matrix.config.ext }}
      NAME: ${{ matrix.config.simple_name }}
      BINARY: ${{ matrix.binaries }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(inputs.matrix) }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Download artifact from compilation
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ matrix.config.simple_name }} ${{ matrix.binaries }}
          path: ${{ matrix.config.simple_name }} ${{ matrix.binaries }}

      - name: Create Package
        run: |
          mkdir crystal

      - name: Download wiki
        run: |
          git clone https://github.com/official-stockfish/Stockfish.wiki.git wiki
          rm -rf wiki/.git
          mv wiki crystal/

      - name: Copy files
        run: |
          mv "${{ matrix.config.simple_name }} ${{ matrix.binaries }}" crystal-workflow
          cd crystal-workflow
          cp -r src ../crystal/
          cp -r scripts ../crystal/
          cp stockfish-$NAME-$BINARY$EXT ../crystal/
          cp "Top CPU Contributors.txt" ../crystal/
          cp Copying.txt ../crystal/
          cp AUTHORS ../crystal/
          cp CITATION.cff ../crystal/
          cp README.md ../crystal/
          cp CONTRIBUTING.md ../crystal/

      - name: Create tar
        if: ${{ startsWith(matrix.config.archive_ext, 'tar') }}
        run: |
          chmod +x ./crystal/crystal-$NAME-$BINARY$EXT
          tar -cavf crystal-$NAME-$BINARY."${{ matrix.config.archive_ext }}" crystal

      - name: Create zip
        if: ${{ matrix.config.archive_ext == 'zip' }}
        run: |
          zip -r crystal-$NAME-$BINARY.zip crystal

      - name: Upload Draft Release Asset
        if: inputs.release_tag != ''
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        with:
          tag_name: ${{ inputs.release_tag }}
          draft: true
          prerelease: ${{ inputs.release_prerelease }}
          files: crystal-${{ matrix.config.simple_name }}-${{ matrix.binaries }}.${{ matrix.config.archive_ext }}
          token: ${{ secrets.token }}
